import type { Config } from 'tailwindcss';
import { colors } from './tokens/js/colors.js'; // generated by Style-Dictionary

const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}', './stories/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors,
      borderRadius: {
        sm: 'var(--alias-semantic-border-radius-sm)',
        md: 'var(--alias-semantic-border-radius-md)',
        lg: 'var(--alias-semantic-border-radius-lg)',
      },
      spacing: {
        'btn-x': 'var(--responsive-spacing-padding-md)',
        'btn-y': 'var(--responsive-spacing-padding-sm)',
      },
      fontSize: {
        sm: ['var(--typography-body-sm-regular-font-size)', 'var(--typography-body-sm-regular-line-height)'],
        base: ['var(--typography-body-md-regular-font-size)', 'var(--typography-body-md-regular-line-height)'],
        lg: ['var(--typography-body-lg-regular-font-size)', 'var(--typography-body-lg-regular-line-height)'],
      },
    },
  },
  plugins: [],
};
export default config;